device: 'cuda'
local_energy_version: "CPP_GPU"

n_samples: 12288000
n_epoches: 30000
save_model: 0
save_per_epoches: 500
load_model: 0
checkpoint_path: "checkpoints/h10_sto6g_1.84-d64L6h4-1.64L0-iter6000-rank0.pt"

do_ham: 0

model_fp: fp32

transfer_learning: false
seed: 333
pos_independ: false
use_sr: false
verbosity: 1
use_clip_grad: false
psi_type: 'complex'
only_infer: false
search_init_best_seed: false
weak_scaling: false

use_uniq_sampling_parallel: false
incr_per_epoch: 50
min_partition_samples: 64
partition_algo: 'number'

max_transfer: 0

use_samples_recursive: true
n_samples_min: 1e4
n_samples_max: 1e12
n_unq_samples_min: 6e3
n_unq_samples_max: 5e4
n_samples_scale_factor: 1.3

drop_samples: false
drop_samples_eps: 1e-8

use_amp_infer_batch: true
amp_infer_batch_size: 2048

use_kv_cache: false
use_grad_accumulation: false
grad_accumulation_width: 2048

sampling_algo: "bfs"
sampling_dfs_width: 128
sampling_dfs_uniq_samples_min: 2048

use_restricted_hilbert: true
qubit_order: -1
log_level: 'INFO'
system: 'LiH'
n_elecs: 4
elec_cons_method: 0

model:
    d_model: 32
    n_layers: 4
    n_heads: 4
    p_dropout: 0.0

use_phase_embedding: false
    
optim:
    name: 'AdamW'
    lr: 1.0
    betas: [0.9, 0.99]
    eps: 1e-9
    weight_decay: 0.00
    open_lr_scheduler: true
    warmup_step: 4000
